test_that("pprof_sitrep() and helpers", {
  expect_message(pprof_sitrep(), regexp = "pprof path")
  expect_message(found_pprof_path(), regexp = "pprof path")
  expect_message(found_pprof_env_new(), regexp = "PROFFER_PPROF_PATH")
  expect_message(found_pprof_env_old(), regexp = "prof_path")
  expect_message(found_pprof_sys(), regexp = "pprof system path")
  expect_message(found_go_path(), regexp = "Go path")
  expect_message(found_go_bin_path(), regexp = "Go binary path")
  expect_message(found_go_bin_env(), regexp = "PROFFER_GO_PATH")
  expect_message(found_go_bin_sys(), regexp = "Go binary system path")
  expect_message(found_graphviz_path(), regexp = "Graphviz path")
  expect_message(found_graphviz_env(), regexp = "PROFFER_GRAPHVIZ_PATH")
  expect_message(found_graphviz_sys(), regexp = "Graphviz system path")
  expect_message(missing_pprof_path(), regexp = "pprof path")
  expect_message(missing_pprof_env_new(), regexp = "PROFFER_PPROF_PATH")
  expect_message(missing_pprof_env_old(), regexp = "prof_path")
  expect_message(missing_pprof_sys(), regexp = "pprof system path")
  expect_message(missing_go_path(), regexp = "Go path")
  expect_message(missing_go_bin_path(), regexp = "Go binary path")
  expect_message(missing_go_bin_env(), regexp = "PROFFER_GO_PATH")
  expect_message(missing_go_bin_sys(), regexp = "Go binary system path")
  expect_message(missing_graphviz_path(), regexp = "Graphviz path")
  expect_message(missing_graphviz_env(), regexp = "PROFFER_GRAPHVIZ_PATH")
  expect_message(missing_graphviz_sys(), regexp = "Graphviz system path")
})
